# Creates the shared network used by all the services
# Dummy service need otherwise network is ignore
# this is equivalent to creating the network on the command line
# docker network create --driver bridge local_ai_network
# docker compose file in each of the stacks must be run separately
services:
  dummy:
    image: busybox
    command: sleep 1
    networks:
      - local_ai_network

networks:
  local_ai_network:
    name: local_ai_network
    driver: bridge
