version: "3.3"
services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    image: ollama/ollama
  mcpo:
    build: .
    container_name: mcpo
    image: ghcr.io/alephpiece/mcpo
    ports:
      - 8000:8000
    volumes:
      - /config/mcpo-config/config.json:/app/config.json
volumes:
  ollama: {}
networks: {}
