services:

  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    entrypoint: >
      sh -c "
      ollama serve &
      sleep 3 &&
      ollama pull qwen2.5:7b-instruct-q4_K_M &&
      wait
      "
    networks:
      - local_ai_network
#  mcpo:
#    build: .
#    container_name: mcpo
#    image: ghcr.io/alephpiece/mcpo
#    ports:
#      - 8000:8000
#    volumes:
#      - /config/mcpo-config/config.json:/app/config.json
volumes:
  ollama: {}

networks:
  local_ai_network:
    external: true
    name: local_ai_network
